### ISSUE TITLE
Make %p python path default

### ISSUE THREAD

**Issue by galgalesh** [AtomLinter/linter-pylint#67]
### Steps to reproduce:

1. Write python script that uses module in same folder.
2. Check errors
3. Try to run the code

### What I get:

- Code runs fine
- Linter gives error

### What I expect:

- Code runs fine
- Linter gives no error

The default module searching behavior of the linter should be the same as that of Python itself. This is currently not the case, since `%p` is not added to the path. Is there a reason for this?

**Comment by galgalesh** [comment]
related: https://github.com/AtomLinter/linter-pylint/issues/58

**Comment by SpainTrain** [comment]
> Write python script that uses module in same folder.

You are talking about relative imports right?  A fully qualified import should work.  As you saw, relative imports are reported in #58 and fixed in the soon-to-be merged https://github.com/AtomLinter/linter-pylint/pull/61.

> since %p is not added to the path

For context, the project directory (`%p`) is added to the path (https://github.com/AtomLinter/linter-pylint/blob/master/lib/main.coffee#L69).  This is why the fully qualified/absolute import should work (and please open another issue if not!).  However, the problem is that this isn't sufficient to mirror the behavior of module searching in Python.  #61 sufficiently mirrors the behavior and I'll see to getting it merged/released soon!

**Comment by galgalesh** [comment]
I have a hard time understanding whether I am doing something wrong or there is a bug. My knowledge about Python and Atom isn't much and Atom has a very confusing definition of what a project is (+ you have "project home" setting, which doesn't have to do with "projects" aka "the folder you have open"..?)

Let my try to explain what I expect to happen: I have two files in one directory. The `test` directory is the root directory that is open in atom.

    test
    |- importer.py
    |- tester.py

tester.py:

    def test1():
        print "test1"

importer.py:

    #!/usr/bin/python
    import tester
    tester.test1()

When I execute importer.py I see 'test1", so it works. However, I still get the error *F0401 Unable to import tester* in Atom.

I have no idea if this is a relative or absolute import, since those terms are mostly used when talking about packages. I do not think this is considered a package, just two files in the same directory. The import is "absolute" compared to the project directory (if "project directory" means "root directory in atom"?)...

I'm sorry for my lack of understanding, but a lot of the terms used here have confusing/implicit definitions. Feel free to explain them for me...

**Comment by SpainTrain** [comment]
Ok, I see now.  This is different than #58, but I think that #61 may still actually fix this issue as well.  We will leave this issue open and see whether #61 manages to fix it.

**Comment by miigotu** [comment]
#61 Does not fix the import problems for me. Ive tried a whole mess of different paths in the "Python Path" setting in linter-python settings and nada, still F0401

**Comment by romanchyla** [comment]
I think you should consider the negative consequences of messing with PYTHONPATH: #104

**Comment by miigotu** [comment]
Still messed up for me too. No matter what I put in the pythonpath setting I get F0401 for any imports not coming from site-packages. pylint on the command line does not give this error.

Im going to try and patch my local copy and see if I can fix it, its super annoying. Im not even using any custom sys.path

**Comment by Arcanemagus** [comment]
I'm marking this as a duplicate of #58 since the root cause is the same, even if the steps to reproduce aren't _exactly_ the same (just almost the same...).

More explanation soon to be posted over there.
